<a href="https://colab.research.google.com/github/IlTACK-OH/numpy_Practice/blob/main/numpy_day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy_day3

In [2]:
import numpy as np

## 21. astype
arr 배열은 float64 타입입니다. 이를 `np.int32` 타입으로 변경하세요.

In [10]:
arr1= np.array([1.1,2.1,3.1])
arr2 = arr1.astype(np.int32)
print('arr1 dtype:',arr1.dtype)
print('arr2 dtype:',arr2.dtype)

arr1 dtype: float64
arr2 dtype: int32


## 22. linspace
0~10 사이를 구간을 20개의 포인트로 분할한 결과를 `ndarray`로 표현하라

In [12]:
np.linspace(0,10,20)
# linspace는 정해진 구간을 정해진 포인트만큼 등간격으로 분할한다.

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## 23. 로우 인덱싱
다음의 `ndarry` 객체에서 마지막 로우(`[6, 7, 8]`)을 출력하세요.

In [14]:
arr = np.arange(9).reshape(3, 3)
arr[2,:] # 나의 답

array([6, 7, 8])

In [16]:
arr[-1] # 답지 답안

array([6, 7, 8])

In [17]:
arr[2] # 답지 답안

array([6, 7, 8])

## 24. 컬럼 인덱싱
다음의 `ndarry` 객체에서 두 번째 컬럼(`[1, 4, 7]`)을 출력하세요.

In [19]:
arr = np.arange(9).reshape(3, 3)
arr[:,1]

array([1, 4, 7])

## 25. 데이터 인덱싱
다음의 `ndarray`객체에서 `17`을 선택하는 코드를 작성하라.

In [21]:
arr = np.arange(25).reshape(5, 5)
arr[3][2] 
arr[3,2] # 한 번에 인덱싱하는 것이 성능 측면에서 유리하다.

17

## 26. 슬라이싱1
`[1 3]`을 슬라이싱 하는 코드를 작성하세요.

In [25]:
arr = np.arange(5)
arr[[1,3]] # 특정 위치의 값을 슬라이싱
arr[1::2] # 증감폭을 지정하여 연속된 데이터 슬라이싱

array([1, 3])

## 27. 슬라이싱2
`[6 7 8 9]`를 슬라이싱 하는 코드를 작성하세요.



In [27]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arr[1,1:]

array([6, 7, 8, 9])

## 28. 슬라이싱 3
첫번째와 두번째 컬럼을 슬라이싱하는 코드를 작성하세요.

In [30]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr[:,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

## 29. 슬라이싱 4
`6`,`7`,`11`,`12` 를 `2x2 ndarray`로 슬라이싱하는 코드를 작성하세요.

In [37]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

## 30. 슬라이싱 5
`0`,`3`,`20`,`23`를 2X2 `ndarray`로 슬라이싱하는 코드를 작성하세요.

In [60]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [91]:
arr[[0,-1],0::3]

array([[ 0,  3],
       [20, 23]])

## 31. ndarray 곱셈
전체 데이터에 10을 곱한 결과를 `ndarray`에 저장하세요.

In [93]:
data = [1,2,3]
result = np.array(data)*10
result

array([10, 20, 30])

그냥 list는 수치연산을 지원하지 않는다. 수치 연산을 위해서는 ndarry로 반환을 먼저하고 수치연산을 진행하자.

## 32. ndarray 제곱
전체 데이터에 제곱한 결과를 `ndarray`에 저장하세요.

In [94]:
data = [1,2,3]
result = np.array(data)**2
result

array([1, 4, 9])

## 33. ndarray 루트
전체 데이터에 루트를 적용한 결과를 `ndarray`에 저장하세요.

In [97]:
data = [1, 2, 3]
result= np.sqrt(np.array(data)) # 다른 방법으론 np.array(data)**(0.5)
result

array([1.        , 1.41421356, 1.73205081])

## 34. ndarray 컬럼 평균
다음 `ndarray`에는 중간고사의 국어점수(10), 영어점수(20), 기말고사의 국어점수(14), 영어점수(16)이 저장돼 있습니다.

In [100]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])

과목별 평균 점수를 출력하세요.

In [103]:
score.mean(axis=0)

array([12., 18.])

## 35. ndarray 로우 표준편차
다음 `ndarray`에는 중간고사의 국어점수(10), 영어점수(20), 기말고사의 국어점수(14), 영어점수(16)이 저장돼 있습니다.

In [ ]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])

중간고사와 기말고사의 표준편차를 출력하세요.

In [104]:
score.std(axis=1)

array([5., 1.])

## 36. 행렬곱
두 행렬의 곱셈결과를 출력하세요.

In [105]:
a = np.arange(4).reshape(2,2)
b = np.arange(1, 5).reshape(2,2)
print("Matrix a:\n",a)
print("Matrix b:\n",b)

Matrix a:
 [[0 1]
 [2 3]]
Matrix b:
 [[1 2]
 [3 4]]


In [110]:
a@b

array([[ 3,  4],
       [11, 16]])

In [112]:
np.matmul(a,b) # MATrix MULtiplication의 줄임말로 외우자

array([[ 3,  4],
       [11, 16]])

## 37. 전치행렬
다음의 `ndarray`로 행과 열의 위치를 바꾼 `전치행렬`을 출력하세요.

In [113]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
arr.T # 나의 답

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [115]:
arr.transpose() # 답지에 있는 또 다른 답

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

## 38. 짝수 배열
다음 배열에서 짝수 값만 추출하세요.

In [118]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
arr[arr%2==0]

array([0, 2, 4, 6, 8])

## 39. 홀수 배열
다음 배열에서 짝수 값만 추출하세요

In [121]:
arr =np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

## 40. 여러 조건
다음 배열에서 3보다 크고 7보다 작은수만 추출하세요

In [124]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
arr[(arr>3)&(arr<7)]

array([4, 5, 6])

## 41. 조건에 맞는 원소값 출력
다음 `ndarray`객체에서 음수를 출력하세요.

In [126]:
arr = np.array([-1, 2, -3, 4])
arr

array([-1,  2, -3,  4])

In [127]:
arr[arr<0]

array([-1, -3])

## 42. 조건에 맞는 원소값 변경 1
다음 `ndarray`객체에서 음수를 0으로 치환하세요.

In [129]:
arr = np.array([-1, 2, -3, 4])
arr[arr<0] = 0
arr

array([0, 2, 0, 4])

## 43. 조건에 맞는 원소값 변경 2
다음 `ndarray` 객체에서 음수를 양수로 변환하세요

In [131]:
arr = np.array([-1, 2, -3, 4])
arr[arr<0] = abs(arr[arr<0])
arr

array([1, 2, 3, 4])

In [135]:
arr = np.array([-1, 2, -3, 4])
abs(arr)

array([1, 2, 3, 4])

## 44. 조건에 맞는 원소값 변경 3
다음 `ndarray`객체에서 양수 혹은 0이면 10을 더하고 음수는 10을 빼세요.

In [134]:
arr = np.array([-1,2,-3,4])
arr[arr>=0] = arr[arr>=0]+10
arr[arr<0] = arr[arr<0]-10
arr

array([-11,  12, -13,  14])

In [137]:
np.where(arr>=0,arr+10,arr-10)

array([-11,  12, -13,  14])

`np.where`은 주어진 조건에 따라서 True인 경우 X를 그렇지 않은 경우는 y를 출력한다. 위의 코드에서는 X = arr+10, y = arr-10이 된다.

## 45. shuffle
numpy random 모듈의 shuffle 함수를 사용해서 입력 리스트의 원소들을 랜덤하게 섞어 보세요.

In [152]:
arr = [1, 2, 3, 4, 5]

In [157]:
from numpy.random import shuffle
arr = np.array(arr)
shuffle(arr)
arr

array([3, 5, 2, 4, 1])

shuffle 함수는 말그대로 배열을 섞어주기만하고 출력은 안하는 것 같다.

## 46. argmin
다음 넘파일 배열에서 최솟값의 인덱스를 출력하세요.

In [167]:
arr = np.array([1, 2, 3, 4, 5])
arr.argmin()

0

## 47. argmax
다음 넘파일 배열에서 최댓값의 **인덱스**를 출력하세요.

In [158]:
arr = np.array([1,2,3,4,5])
arr.argmax()

4

## 48. 정렬
다음 넘파이 배열을 오름차순 정렬해보세요.

In [162]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

## 49. numpy.vstack
numpy.vstack 함수를 사용하여 다음 2차원 배열을 생성하세요.

In [163]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

In [166]:
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4]])

`vstack`은 array를 수직하게(행방향)으로 쌓는 명령어이다.

## 50. flatten
flatten 메서드를 사용하여 다음 배열을 1차원 배열로 변경하세요.

In [169]:
arr = np.array([[1, 2],[3, 4]])

In [170]:
arr.flatten()

array([1, 2, 3, 4])