<a href="https://colab.research.google.com/github/IlTACK-OH/numpy_Practice/blob/main/numpy_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day1

## 1. 넘파이 임포트
넘파이 모듈을 np라는 이름으로 임포트해보세요.

In [1]:
import numpy as np

## 2. ndarray
리스트를 넘파이의 ndarray 객체로 변환해보세요.<br>
data = [1, 2, 3]

In [3]:
data = [1,2,3]
np.array(data)

array([1, 2, 3])

## 3. arange
0부터 99까지의 정수가 저장된 ndarray 객체를 만들어 보세요.

In [12]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## 4. arange
구구단 3단의 결과가 저장된 ndarray 객체를 만들어 보세요.
> arr
[ 3  6  9 12 15 18 21 24 27]


In [15]:
np.arange(1,10)*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

## 5. arange
1000보다 작은 짝수가 저장된 ndarray 객체를 만들어 보세요.

In [18]:
np.arange(2,1000,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208,
       210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234,
       236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260,
       262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286,
       288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312,
       314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338,
       340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 36

## 6. 실수 range
0부터 1까지 0.1 간격으로 구성된 ndarray를 생성해보세요. 1은 포함되지 않습니다.

In [19]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

## 7. reshape
리스트에는 6개의 데이터가 저장돼 있습니다.
> data = [0, 1, 2, 3, 4, 5]

다음과 같이 2행 3열의 ndarray로 변환하세요.

>[[0 1 2]<br>
 [3 4 5]]

In [21]:
data = [0, 1, 2, 3, 4, 5]
np.array(data).reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

## 8. reshape
다음의 2차원 ndarray 1차원 ndarray로 변환하세요.

> arr = np.array([<br>
    [0, 1, 2],<br>
    [3, 4, 5]<br>
])

In [25]:
arr = np.array([
[0, 1, 2],
[3, 4, 5]
])

print(arr.reshape(6))
print(arr.flatten())

[0 1 2 3 4 5]
[0 1 2 3 4 5]


## 9. reshape
주어진 ndarray를 다음과 같이 변경해 보세요.

arr = np.arange(3)

[[0]<br>
 [1]<br>
 [2]]

In [27]:
arr = np.arange(3)
arr.reshape(3,1)

array([[0],
       [1],
       [2]])

## 10. 에러의 원인을 설명하세요.

> np.arange(6).reshape(2, 4)
ValueError: cannot reshape array of size 6 into shape (2,4)

6개의 데이터를 가지고 8개의 데이터가 필요한 행렬을 만들려고해서. 데이터의 갯수가 부족해서 Error발생.

## 11. 2차원 배열
다음과 같이 2차원 ndarray 객체를 정의하세요.

>[[0 1 2]<br>
 [3 4 5]]

In [31]:
np.array([[0,1,2],[3,4,5]])

array([[0, 1, 2],
       [3, 4, 5]])

## 12. ones
1이 20개 저장된 아래의 ndarray 객체를 만들어 보세요.

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

In [36]:
print("using array:",np.array([1]*20))
print("or")
print("using ones:",np.ones(20,dtype=int))

using array: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
or
using ones: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## 13. ones
4행 5열로 저장된 아래의 ndarray 객체를 만들어 보세요.

>[[1 1 1 1 1]<br>
 [1 1 1 1 1]<br>
 [1 1 1 1 1]<br>
 [1 1 1 1 1]]

In [33]:
np.array([1]*20).reshape((4,5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.ones(20,dtype=int).reshape((4,5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 14. ones
255로 채워진 10X10 크기의 ndarray 객체를 생성하세요.

In [40]:
(np.ones(100,dtype=int)*255).reshape((10,10))

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

## 15. zeros
3x4 (행x열) 크기의 0으로 채워진 배열을 생생해보세요.

In [46]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 16. dtype
[1, 2, 3]을 np.int32 타입의 ndarray 배열로 생성하세요.

In [50]:
np.ndarray([1,2,3],dtype=np.int32)

array([[[1, 0, 2],
        [0, 3, 0]]], dtype=int32)

## 17. dtype
다음 배열의 데이터 타입을 확인해보세요.

arr = np.array([1, 2, 3])

In [53]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

## 18. dtype
다음 배열의 데이터 타입을 확인해보세요.

arr = np.array(['1', '2', '3'])

In [55]:
arr = np.array(['1', '2', '3'])
arr.dtype

dtype('<U1')

`U1`은 1바이트 문자열이라는 의미이다. 참고로 1바이트는 8비트이다.

## 19. dtype
다음 데이터를 np.int16 타입의 배열로 형변환하세요.

arr = np.array([1, 2, 3])

In [57]:
arr = np.array([1, 2, 3])
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

## 20. 데이터 타입
300이 44로 출력되는 이유를 설명하세요.

> a = np.array( [ 255, 300, 128], dtype=np.uint8 )<br>
 a
[255  44 128]

`uint8`은 부호 없는 8비트 정수를 표현한다. 즉 $2^8-1$범위의 수를 표현할 수 있기 때문에 300은 이 범위를 넘어서 잘못된 값이 출력된다.